### ISSUE TITLE
Readme code consistency + function assignment doubt

### ISSUE THREAD

**Issue by robertoetcheverryr** [pablomartinezm/jsonipy#4]
Hi,

I'm pretty new to Python, coming from an assembler and ANSI C background. I found this module very interesting for what I needed, so I've been tinkering a bit with it.
In the first two examples in the readme, you define the dictionary with dict(), then you change to {}. I actually had to search for the difference, so I learnt something, but shouldn't it be consistent from one example to the next? 
Now, to my main question:
Why aren't read, write, _get_att_composedm, _get_att_name and _create_attribute either assigned inside the class or at least defined inside and assigned outside?
I ask this because PyCharm correctly nags me about a missing definition and autocomplete fails due to read and write only existing after the module's initialization.
I actually tested adding read and write's definition inside and nothing seems to have broken...

Best Regards,
Roberto

**Comment by pablomartinezm** [comment]
About the first thing, the intention was to show that you can work with common dictionaries, no matter how you declare them it makes no difference, but you're right, it should be consistent.

About the second one is just a trick to split semantically the library in different files, it has nothing to do with functionality but with readability of code, I know that this collides with code editors, if you have a better proposal fork the repo and make a pull request :)
