### ISSUE TITLE
How should I setup if I want an attribute to be None (if not present)

### ISSUE THREAD

**Issue by axcosta** [pablomartinezm/jsonipy#6]
Would it be possible to have an attribute returning None if actual JSON has None (eventually) as attribute value? Currently when it is happening, the error `jsonizable.exceptions.MissingPropertyException` pops up.

**Comment by pablomartinezm** [comment]
I'm not sure about what do you exactly want. Can you provide us an example?

**Comment by axcosta** [comment]
Yes, sure! Maybe just me not being able to use it properly 😊. I've got a
class with an attribute "labels" which is of type `dict`, but it is not
always set up on source json. So when it is not there, I want it to be set
as None (as default). I tried defining it as optional (with that handy
question mark) but it doesn't work bc current third-party component code
breaks saying attribute does not exist. Hope it is clear now.

Em qua, 27 de mai de 2020 05:41, Pablo Martinez <notifications@github.com>
escreveu:

**Comment by pablomartinezm** [comment]
I will provide you an exampe:

```python

class Object(Jsonizable):
    class Meta:
        schema = {
            "optional_dict?": dict,
            "required_dict": dict,
        }

my_json = {
    "optional_dict": None,
    "required_dict": {},
}
obj = Object(my_json)
print(obj.optional_dict)
>> None

print(obj.required_dict)
>> {}

print(obj.write())
>> {'required_dict': {}}
```

I guess that you want to write a default value when there is no such `optional_dict` present in the JSON file. At the moment there is no such option. The best approach is overwriting the write function:

```python
class Object(Jsonizable):
    class Meta:
        schema = {
            "optional_dict?": dict,
            "required_dict": dict,
        }
    
    def write(self):
        val = super().write()
        if not self.optional_dict:
            val["optional_dict"] = {}
        return val

my_json = {
    "optional_dict": None,
    "required_dict": {},
}

obj = Object(my_json)
print(obj.write())
>> {'required_dict': {}, 'optional_dict': {}}
```

**Comment by axcosta** [comment]
Yes, @pablomartinezm , that's exactly what I was looking for. Thank you very much!
